### ISSUE TITLE
Requests for characters / realms with accents causes body undefined

### ISSUE THREAD

**Issue by viglucci** [benweier/battlenet-api#11]
Making a fetch call to a character that has a utf8 accented character in their name causes the res body to be 'undefined'.

Example characters:

```
var payload = {
  "region": "us",
  "realmSlug": "alterac-mountains",
  "name": "Facelìft",
}

var params = {
  "origin": payload.region,
  "realm": payload.realmSlug,
  "name": payload.name
};

bnet.wow.character.statistics(params, callback);

function callback(err, body){
  //body is undefined
}
```

If there is something I am doing wrong / something I need to be doing please LMK. 

Thanks.

**Comment by kafoso** [comment]
- By default, Javascript hoists functions. Even so, did you try to move the `callback` function above the API request line?
- Did you check if `err` contains any information?

**Comment by viglucci** [comment]
err is null.

I am able to successfully make calls with characters whos names do not contain accented characters, I do not think the positioning of the function definition has any affect.

**Comment by benweier** [comment]
Thanks @viglucci I think I know what the issue is so I'll test my theory tonight and probably push a fix out tomorrow.

**Comment by viglucci** [comment]
Thanks Ben!

Looking forward to an update.

**Comment by benweier** [comment]
Hey @viglucci My suspicion was correct and the character encoding is what's causing the API request to fail. I've been able to test a successful request by calling the character method with a URI encoded value.

```javascript
var params = {
  origin: 'us',
  realm: 'alterac-mountains',
  name: encodeURIComponent('Facelìft')
};

bnet.wow.character.statistics(params, callback);
```

While looking at fixing the issue I realised there are some potentially far-reaching consequences. Some developers may perform their own encoding while others may not, so I would like to provide automatic encoding by default with an option to disable it.

I think I can also improve the request methods so that I'm not adding a bunch of duplicate `encodeURIComponent()` calls but route all requests through a single function to properly encode all of the API parameters.

**Comment by viglucci** [comment]
I might suggest not encoding by default, with an option to enable the encoding. Most of the battle.net API libraries I've used in the past have required the developer to provide the properly encoded strings.

**Comment by benweier** [comment]
Thanks @viglucci I'll take that into consideration. Perhaps the best thing is to put an encoding recommendation into the documentation. At the very worst, developers who don't encode their input simply get no results.

**Comment by benweier** [comment]
@viglucci because of the relative low impact of adding optional parameter encoding, I've added some info to the documentation and will leave it at that. Thanks again :)
