### ISSUE TITLE
Unable to get China origin for "bnet.wow.pvp.leaderboards"

### ISSUE THREAD

**Issue by moderncodes** [benweier/battlenet-api#7]
Possible wrong URL identifier in pvp.js
URL for China should be:
CH => http://www.battlenet.com.cn/api/wow/leaderboard/..
unlike others
US => http://us.battle.net/api/wow/leaderboard/..
EU => http://eu.battle.net/api/wow/leaderboard/..
KR => http://kr.battle.net/api/wow/leaderboard/..
TW => http://tw.battle.net/api/wow/leaderboard/..

**Comment by benweier** [comment]
Thanks @moderncodes 

The documentation doesn't include the China API in the supported endpoints. Initially this was due to incomplete availability of features available for the other origins. I also need to confirm whether there are any differences to the China API between the other origins.

I'm currently testing an update that will make the China API available in v0.9.0
